version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: saif
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: db
  app:
    build: .
    ports:
      - 8082:8082
    depends_on:
      - db
  
volumes:
  db_data: {}